version: '3.4'

services:
  
  productos:
    image: wilbrenrosario/productos:latest
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - ordenes
  ordenes:
    image: wilbrenrosario/ordenes:latest
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  