name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Compose Build
      run: docker-compose build .
    - name: Message
      run: echo "Todo Ok!"  
